HOSTNAME_ROOT = "http://localhost:8090"
POST_HEADERS = {"Content-type": "application/json"}

INDEX_ENDPOINT = "/"
TRANSACTIONS_ENDPOINT = "/transactions"
POSITIONS_ENDPOINT = "/positions"
TRANSACTION_ENDPOINT = "/transaction"

FIELD_TICKER = "ticker"
FIELD_PRICE = "price"
FIELD_QUANTITY = "quantity"

FREQUENCY_DAILY = "1d"

COLUMN_CLOSE = "Close"
COLUMN_DATE = "Date"
COLUMN_SPREAD = "spread"
COLUMN_ZSCORE = "zscore"
COLUMN_MA_ZSCORE = "_ma_" + COLUMN_ZSCORE

COINTEGRATION_THRESHOLD = 0.025
ADFULLER_TOLERANCE = 0.05
