HOSTNAME_ROOT = "http://localhost:8090"
POST_HEADERS = {"Content-type": "application/json"}

INDEX_ENDPOINT = "/"
TRANSACTIONS_ENDPOINT = "/transactions"
POSITIONS_ENDPOINT = "/positions"
TRANSACTION_ENDPOINT = "/transaction"

SPY_HOLDINGS_FILE = "src/client/spy_holdings.csv"

FIELD_TICKER = "ticker"
FIELD_PRICE = "price"
FIELD_QUANTITY = "quantity"

FREQUENCY_DAILY = "1d"

COLUMN_SECTOR = "Sector"
COLUMN_TICKER = "Ticker"
COLUMN_WEIGHT = "Weight"
COLUMN_CLOSE = "Close"
COLUMN_DATE = "Date"
COLUMN_SPREAD = "spread"
COLUMN_ZSCORE = "zscore"
COLUMN_MA_ZSCORE = "_ma_" + COLUMN_ZSCORE
COLUMN_MOMENTUM = "momentum"

COINTEGRATION_THRESHOLD = 0.025
ADFULLER_TOLERANCE = 0.05

ANCHOR_Z_SCORE = 0
HORIZONTAL_LINE_STYLE = "--"
HORIZONTAL_LINE_COLOR = "black"

SECTOR_INFORMATION_TECHNOLOGY = "Information Technology"
SECTOR_CONSUMER_DISCRETIONARY = "Consumer Discretionary"
SECTOR_COMMUNICATION_SERVICES = "Communication Services"
SECTOR_FINANCIALS = "Financials"
SECTOR_HEALTH_CARE = "Health Care"
SECTOR_CONSUMER_STAPLES = "Consumer Staples"
SECTOR_ENERGY = "Energy"
SECTOR_UTILITIES = "Utilities"
SECTOR_MATERIALS = "Materials"
SECTOR_INDUSTRIALS = "Industrials"
SECTOR_REAL_ESTATE = "Real Estate"
SECTOR_UNASSIGNED = "Unassigned"
